- name: "potential bug"
  description: Bug reported but yet to be analysed
  color: f9d0c4
- name: "confirmed bug"
  description: Bug reproduced and needs to be fixed
  color: b60205
- name: "question"
  description: Get support, ask questions
  color: d876e3
- name: "request"
  description: New feature or request
  color: 0052cc
- name: "feedback"
  description: Release feedback
  color: 79db55
- name: "not plugin"
  description: Issue or feature request out of my control
  color: fbca04
- name: "unreproduced"
  description: Unable to reproduce issue
  color: c5def5
- name: "solved"
  description: Solved, but not yet released.
  color: 0e8a16
- name: "awaiting information"
  description: More information requested about the report
  color: d4c5f9
- name: "under construction"
  description: Issue/FR grabbed and someone else is working on it
  color: c96426
- name: "duplicate"
  description: Issue/FR already exists
  color: cfd3d7
- name: "documentation"
  description: Something to do with documentation
  color: 1d76db
- name: "upstream library"
  description: Something's wrong with an upstream library the plugin is using
  color: fbca04
- name: "grabbed"
  description: Issue/FR has been grabbed by a member of the community
  color: 5319e7
- name: "up for grabs"
  description: Issue/FR will not be worked on, open for a member of the community to take it on
  color: fbca04
- name: "needs triage"
  description: Issue needs manual triage (aka bot couldn't do it...)
  color: fbca04
- name: "needs review"
  description: Yet to be reviewed
  color: fff699
- name: "improvement"
  description: "Improvement to existing functionality"
  color: 63d681
