- name: "type: potential bug"
  description: Bug reported but yet to be analysed
  color: f9d0c4
- name: "type: confirmed bug"
  description: Bug reproduced and needs to be fixed
  color: b60205
- name: "type: question"
  description: Get support, ask questions
  color: d876e3
- name: "type: request"
  description: New feature or request
  color: 0052cc
- name: "type: feedback"
  description: Release feedback
  color: 79db55
- name: "type: not plugin"
  description: Issue or feature request out of my control
  color: fbca04
- name: "status: unreproduced"
  description: Unable to reproduce issue
  color: c5def5
- name: "status: solved"
  description: Solved!
  color: 0e8a16
- name: "status: awaiting information"
  description: More information requested about the report
  color: d4c5f9
- name: "status: under construction"
  description: Issue/FR grabbed and someone else is working on it
  color: c96426
- name: "duplicate"
  description: Issue/FR already exists
  color: cfd3d7
- name: "documentation"
  description: Something to do with documentation
  color: 1d76db
- name: "type: upstream library"
  description: Something's wrong with an upstream library the plugin is using
  color: fbca04
