name: Label Sync
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - cp2004/OctoPrint-WS281x_LED_Status
          - cp2004/Octoprint-Upgrade-To-Py3
          - cp2004/OctoPrint-EEPROM-Marlin
          - cp2004/OctoPrint-VirtualPrinterSettings
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repository }}
          token: ${{ secrets.PERSONAL_TOKEN }}
