name: Label Sync
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - jneilliii/github_management
          - jneilliii/OctoPrint-BackupScheduler
          - jneilliii/OctoPrint-GoogleDriveBackup
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repository }}
          token: ${{ secrets.PERSONAL_TOKEN }}
